import { expect, test } from "bun:test";
import { Context, parseAndEvaluate, parseAndEvaluateAsync } from "../../rix/src/index.js";
import { UNDECIDED } from "../../rix/src/runtime/decision.js";

for (const [mode,evaluate] of [["sync",parseAndEvaluate],["async",parseAndEvaluateAsync]]) {
    test(`${mode}: core mathematics tutorial cells execute in order`, async () => {
        const source = await Bun.file(new URL("../tutorials/core-mathematics.md",import.meta.url)).text();
        const cells = [...source.matchAll(/^```rix edu\n([\s\S]*?)^```/gm)].map(match=>match[1]);
        const context = new Context();
        const results = [];
        for (const cell of cells) results.push(await evaluate(cell,{context}));
        expect(results.length).toBeGreaterThanOrEqual(3);
        expect(results[0].values[0].value).toBe(1n);
        expect(results[1].values[0].value).toBe(5n);
        expect(results[2].value).toBe(1n);
        expect(results[3].values.slice(0,3).map(value=>value.value)).toEqual([7n,1n,1n]);
        expect(results[4].values[0]).toBeNull();
        expect(results[4].values[1].value).toBe(1n);
        expect(results[4].values[2]).toBe(UNDECIDED);
        expect(results[5].values[0]).toBeNull();
        expect(results[5].values[1].value).toBe(1n);
        expect(results[6].values[0].value).toBe(1n);
        expect(results[6].values[1]).toBeNull();
        expect(results[7].values[0].value).toBe(1n);
        expect(results[8].values[0].value).toBe(1n);
        expect(results[8].values[1].value).toBe("desc");
        expect(results[8].values[2]).toBeNull();
        expect(results[9].values[0]).toBeNull();
        expect(results[10].values[0].value).toBe("unresolved");
        expect(results[10].values[1]).toBeNull();
        expect(results[10].values[2]).toBe(UNDECIDED);
        expect(results[11].values[0].value).toBe("setEnclosure");
        expect(results[11].values[1]).toBe(UNDECIDED);
        expect(results[11].values[2]).toBeNull();
        expect(results[11].values[3].value).toBe(1n);
        expect(results[12].values[0].value).toBe("operator");
        expect(results[12].values[1].value).toBe("exactScalar");
        expect(results[12].values[2].value).toBe(1n);
        expect(results[13].values.slice(0,3).map(value=>value.value)).toEqual([1n,1n,1n]);
        expect(results[13].values[3].value).toBe("refinableReal");
        expect(results[13].values[4].value).toBe("operator");
        expect(results[14].values[0].value).toBe("budgetExhausted");
        expect(results[14].values[1].value).toBe(1n);
        expect(results[14].values[2]).toBeNull();
        expect(results[15].values.slice(0,2).map(value=>value.value)).toEqual([1n,1n]);
        expect(results[15].values[2]).toBeNull();
        expect(results[16].values[0]).toBeNull();
        expect(results[16].values[1].value).toBe("unverifiedImport");
        expect(results[16].values[2].value).toBe("desc");
        expect(results[17].values[0].value).toBe("realSnapshot");
        expect(results[17].values[1]).toBeNull();
        expect(results[17].values[2].value).toBe("unverifiedImport");
        expect(results[18].values[0].value).toBe("complete");
        expect(String(results[18].values[1])).toBe("10");
        expect(results[19].values[0].value).toBe("complete");
        expect(String(results[19].values[1])).toBe("3");
        expect(String(results[19].values[2])).toBe("3");
        expect(results[19].values[3].value).toBe("invalidAssumptions");
        expect(results[20].values[0].value).toBe(1n);
        expect(results[20].values[1].value).toBe("unresolved");
        expect(results[21].values[0].value).toBe("complete");
        expect(String(results[21].values[1])).toBe("16");
        expect(results[21].values[2].value).toBe(1n);
        expect(results[21].values[3]).toBeNull();
        expect(String(results[22].values[0])).toBe("4");
        expect(results[22].values.slice(1).map(v=>v.value)).toEqual(["unresolved","unresolved"]);
        expect(results[23].values.slice(0,2).map(v=>v.value)).toEqual(["unresolved","invalidAssumptions"]);
        expect(results[23].values[2]).toBeNull();
        expect(String(results[24].values[0])).toBe("1/4");
        expect(results[24].values[1].value).toBe("invalidAssumptions");
        expect(String(results[24].values[2])).toBe("1");
        expect(results[24].values[3].value).toBe("desc");
        expect(results[25].values[0].value).toBe("unresolved");
        expect(String(results[25].values[1])).toBe("3/2");
        expect(String(results[25].values[2])).toBe("1");
        expect(results[26].values.slice(0,2).map(v=>v.value)).toEqual(["complete","setEnclosure"]);
        expect(results[26].values.slice(2,4).map(String)).toEqual(["1","5"]);
        expect(results[26].values[4].value).toBe("conditional");
        expect(results[27].values.slice(0,2).map(v=>v.value)).toEqual(["complete","exactScalar"]);
        expect(results[27].values[2].value).toBe(1n);
        expect(results[28].values.slice(0,2).map(v=>v.value)).toEqual(["enclosed","singletonEnclosure"]);
        expect(results[28].values[2]).toBeNull();
        expect(results[28].values[3].value).toBe(1n);
        expect(results[28].values[4].value).toBe("conditional");
        expect(results[29].values.map(v=>v.value)).toEqual(["complete",2048n,1024n]);
    });
}
