import { pluginTutorialGroups, pluginTutorials } from "./generated/plugin-tutorial-index.js";

const coreTutorials = [
    { number: "1", file: "getting-started.html", title: "Start with exact numbers", description: "Variables, fractions, and a persistent RiX session." },
    { number: "1a", parent: "1", file: "capstone-exact-recipe.html", title: "Capstone: exact recipe scaling", description: "Combine variables, fractions, intervals, and calculator workflow." },
    { number: "2", file: "collections.html", title: "Collections", description: "A high-level tour of arrays, maps, and sets." },
    { number: "2a", parent: "2", file: "arrays.html", title: "Arrays", description: "Ordered values, one-based indexes, and immutable updates.", object: "array" },
    { number: "2b", parent: "2", file: "maps.html", title: "Maps", description: "Named entries and record-like data.", object: "map" },
    { number: "2c", parent: "2", file: "sets.html", title: "Sets", description: "Unique values and set algebra.", object: "set" },
    { number: "2d", parent: "2", file: "tuples-and-strings.html", title: "Tuples and strings", description: "Positional data and textual values." },
    { number: "2e", parent: "2", file: "tensors.html", title: "Tensors", description: "Structured multidimensional exact data." },
    { number: "2f", parent: "2", file: "capstone-inventory.html", title: "Capstone: exact inventory", description: "Model a small inventory with arrays, maps, and sets." },
    { number: "3", file: "expressions.html", title: "Expressions and exact notation", description: "Operators, exact numbers, intervals, and holes." },
    { number: "3a", parent: "3", file: "operators.html", title: "Operators and precedence", description: "Arithmetic, comparisons, and implicit application." },
    { number: "3b", parent: "3", file: "number-notation.html", title: "Number notation", description: "Repeating decimals, bases, and continued fractions." },
    { number: "3c", parent: "3", file: "intervals.html", title: "Intervals", description: "Exact bounds, uncertainty, and betweenness." },
    { number: "3d", parent: "3", file: "interval-generation.html", title: "Interval generation and sampling", description: "Produce exact ranges, partitions, mediants, and seeded samples." },
    { number: "3e", parent: "3", file: "scoped-randomness.html", title: "Scoped reproducible randomness", description: "Reset, inherit, and locally replace deterministic random streams." },
    { number: "3f", parent: "3", file: "holes.html", title: "Nulls and holes", description: "Undefined values, defaults, and coalescing." },
    { number: "3g", parent: "3", file: "capstone-bounds.html", title: "Capstone: bounds check", description: "Use exact notation, intervals, and safe defaults together." },
    { number: "4", file: "binding.html", title: "Binding and patterns", description: "Cells, assignments, destructuring, and metadata." },
    { number: "4a", parent: "4", file: "cells.html", title: "Cells and assignment", description: "Aliases, copies, updates, and identity." },
    { number: "4b", parent: "4", file: "destructuring.html", title: "Destructuring", description: "Pull structured values into named bindings." },
    { number: "4c", parent: "4", file: "properties.html", title: "Properties and metadata", description: "Receiver-first methods and value annotations." },
    { number: "4d", parent: "4", file: "capstone-ledger.html", title: "Capstone: shared ledger", description: "Use cells, destructuring, and updates in a small model." },
    { number: "5", file: "functions.html", title: "Functions and scope", description: "Callables, multifunctions, closures, and partials." },
    { number: "5a", parent: "5", file: "function-basics.html", title: "Define and call", description: "Functions, lambdas, rest parameters, and spread." },
    { number: "5b", parent: "5", file: "multifunctions.html", title: "Multifunctions", description: "Prepared variants, dispatch, and recursion." },
    { number: "5c", parent: "5", file: "scope.html", title: "Scope and imports", description: "Closures, outer names, and block headers." },
    { number: "5d", parent: "5", file: "partials.html", title: "Partial application", description: "Placeholders and arity-capped callables." },
    { number: "5e", parent: "5", file: "capstone-dispatch.html", title: "Capstone: rule dispatcher", description: "Compose functions, scope, and variants into one task." },
    { number: "6", file: "control.html", title: "Control and deferred work", description: "Ternaries, braces, loops, and deferred execution." },
    { number: "6a", parent: "6", file: "ternaries.html", title: "Ternaries and cases", description: "Choose values with branches, prepared trials, and ordered recovery." },
    { number: "6b", parent: "6", file: "brace-containers.html", title: "Brace containers", description: "Blocks, sigils, loops, and break blocks." },
    { number: "6c", parent: "6", file: "deferred.html", title: "Deferred execution", description: "Delay and evaluate code deliberately." },
    { number: "6d", parent: "6", file: "capstone-simulation.html", title: "Capstone: bounded simulation", description: "Use branches, blocks, and loops to model a process." },
    { number: "7", file: "transformations.html", title: "Transforming data", description: "Pipes, generators, regexes, and embedded values." },
    { number: "7a", parent: "7", file: "pipes.html", title: "Pipes", description: "Map, filter, reduce, and callback context." },
    { number: "7b", parent: "7", file: "generators.html", title: "Generators", description: "Build and filter generated sequences." },
    { number: "7c", parent: "7", file: "lazy-generators.html", title: "Lazy generators", description: "Contrast eager arrays with cached on-demand sequences." },
    { number: "7d", parent: "7", file: "regex-and-strings.html", title: "Regexes and strings", description: "Pattern literals and text transformation." },
    { number: "7e", parent: "7", file: "capstone-report.html", title: "Capstone: transform a report", description: "Turn a small collection into a derived result." },
    { number: "7f", parent: "7", file: "async-concurrency.html", title: "Async and concurrency", description: "Await bounded collection work, stream pipe stages, and start supervised background effects." },
    { number: "8", file: "semantics.html", title: "Semantics, types, and units", description: "Conversions, traits, headers, and dimensions." },
    { number: "8a", parent: "8", file: "conversions.html", title: "Conversions", description: "Ask and convert semantic types." },
    { number: "8b", parent: "8", file: "headers-and-traits.html", title: "Headers and traits", description: "Sticky semantics and protocol bundles." },
    { number: "8c", parent: "8", file: "units.html", title: "Physical units and quantities", description: "Compose units, convert exactly, and catch dimensional mistakes." },
    { number: "8d", parent: "8", file: "exact-generators.html", title: "Exact generators", description: "Keep pi and algebraic roots exact through arithmetic." },
    { number: "8e", parent: "8", file: "complex-numbers.html", title: "Exact complex numbers", description: "Divide, conjugate, and inspect exact complex values." },
    { number: "8f", parent: "8", file: "cayley-polar.html", title: "Exact Cayley polar form", description: "Represent exact complex direction without a transcendental angle." },
    { number: "8g", parent: "8", file: "capstone-measurement.html", title: "Capstone: exact measurement", description: "Combine physical dimensions with an exact symbolic magnitude." },
    { number: "9", file: "system.html", title: "System and symbolic work", description: "Capabilities, assertions, and diagnostics." },
    { number: "9a", parent: "9", file: "system-context.html", title: "System capabilities", description: "The dot object, aliases, and permissions." },
    { number: "9b", parent: "9", file: "assertions-and-symbols.html", title: "Assertions and symbolic specs", description: "Constraints and symbolic construction." },
    { number: "9c", parent: "9", file: "symbolic-calculus.html", title: "Exact symbolic calculus", description: "Compose, differentiate, integrate, and simplify symbolic specs." },
    { number: "9d", parent: "9", file: "structural-arithmetic.html", title: "Structural arithmetic", description: "Use spacing to preserve forms, combine structures, and splice RiX values." },
    { number: "9e", parent: "9", file: "backtick-parsers.html", title: "Backtick parsers and functions", description: "Select notation parsers and turn free symbols into callables." },
    { number: "9f", parent: "9", file: "diagnostics.html", title: "Diagnostics and tests", description: "Warnings, tracing, and test helpers." },
    { number: "9g", parent: "9", file: "capstone-verified-rule.html", title: "Capstone: verified rule", description: "Build a small rule and validate it with system helpers." },
    { number: "10", file: "scripts.html", title: "Scripts and extensions", description: "RiX modules, host boundaries, and language extension." },
    { number: "10a", parent: "10", file: "rix-scripts.html", title: "RiX scripts", description: "Imports, interface bindings, and capability frames." },
    { number: "10b", parent: "10", file: "javascript-modules.html", title: "JavaScript modules", description: "Host modules and the browser trust boundary." },
    { number: "10c", parent: "10", file: "extensions.html", title: "Language extensions", description: "System loaders, keywords, and custom operators." },
    { number: "10d", parent: "10", file: "method-extensions.html", title: "Extend existing types", description: "Add collision-safe receiver methods without patching individual values." },
    { number: "10e", parent: "10", file: "gotcha-tutorial.html", title: "JavaScript-to-RiX gotchas", description: "Translate truth, lazy branches, captures, loops, and immutable values deliberately." },
    { number: "10f", parent: "10", file: "linting.html", title: "Live lint laboratory", description: "Find and repair scope, control-flow, reactive, mathematical, and plugin mistakes." },
    { number: "10g", parent: "10", file: "capstone-package-design.html", title: "Capstone: package design", description: "Design a safe RiX package boundary." },
    { number: "11", file: "problems.html", title: "Problems in four languages", description: "Compare familiar JavaScript, Python, Julia, and RiX solutions." },
    { number: "11a", parent: "11", file: "problem-newton.html", title: "Newton square root", description: "Approximate a root to a supplied tolerance." },
    { number: "11b", parent: "11", file: "problem-fizzbuzz.html", title: "FizzBuzz", description: "Separate branching rules from iteration." },
    { number: "11c", parent: "11", file: "problem-collatz.html", title: "Collatz test", description: "Test a starting value up to a step limit." },
    { number: "11d", parent: "11", file: "problem-primes.html", title: "Prime filtering", description: "Moderate example: generate and filter candidates." },
    { number: "11e", parent: "11", file: "problem-matrix.html", title: "Matrix product", description: "Moderate example: structured numeric data." },
    { number: "11f", parent: "11", file: "problem-symbolic.html", title: "Symbolic differentiation", description: "Advanced example: structured expressions and symbolic rules." },
    { number: "12", file: "structured-output.html", title: "Structured output", description: "Keep tables, documents, slides, and graphics meaningful across RiX hosts." },
    { number: "12a", parent: "12", file: "tables-and-grids.html", title: "Tables and mathematical grids", description: "Present labeled data and textbook-style ruled layouts." },
    { number: "12b", parent: "12", file: "documents-and-slides.html", title: "Documents and slides", description: "Compose report fragments, captions, and portable slide decks." },
    { number: "12c", parent: "12", file: "plots-and-graphics.html", title: "Plots and graphics", description: "Plot exact polynomials and understand portable SVG scenes." },
    { number: "12d", parent: "12", file: "drawing-with-draw.html", title: "Drawing with .Graphics", description: "Build portable scenes from paths, shapes, groups, transforms, and clips." },
    { number: "12e", parent: "12", file: "sheets-and-tensor-views.html", title: "Sheets and tensor views", description: "Navigate exact grids, canonical RiX addresses, and higher-dimensional planes." },
    { number: "12f", parent: "12", file: "interactive-graphics.html", title: "Interactive graphics", description: "Drag a point through the shared widget protocol and watch reactive output change." },
    { number: "12g", parent: "12", file: "control-panels.html", title: "Reactive control panels", description: "Build exact interactive controls on ordinary dollar-reactive RiX values." },
    { number: "12h", parent: "12", file: "reactive-scenes-and-snapshots.html", title: "Reactive scenes and snapshots", description: "Use actions, explicit collection publication, snapshots, and timelines in reusable output." },
    { number: "13", file: "core-host-lowering.html", title: "Core, host, and lowering", description: "See how RiX syntax reaches named operations and capability owners." },
    { number: "13a", parent: "13", file: "core-operations.html", title: "Core operations", description: "Use public PascalCase calls alongside expression syntax." },
    { number: "13b", parent: "13", file: "lazy-core-forms.html", title: "Lazy structural forms", description: "Build assignments, maps, and lambdas from explicit core forms." },
    { number: "13c", parent: "13", file: "lowering-and-ir.html", title: "Lowering syntax", description: "Trace source syntax through IR operations and evaluator dispatch." },
    { number: "13d", parent: "13", file: "host-and-plugins.html", title: "Host objects and plugins", description: "Understand camelCase host roots, registration, and capability boundaries." },
    { number: "13e", parent: "13", file: "capstone-explicit-core.html", title: "Capstone: explicit core", description: "Translate a compact RiX calculation into named core calls." },
];

export const tutorials = [...coreTutorials, ...pluginTutorialGroups, ...pluginTutorials];

export const rootTutorials = tutorials.filter((tutorial) => !tutorial.parent);
export const tutorialByNumber = (number) => tutorials.find((tutorial) => tutorial.number === String(number));
export const childrenOf = (number) => tutorials.filter((tutorial) => tutorial.parent === String(number));
